### ISSUE TITLE
More helpful error when unable to read tls-keystore-file.

### ISSUE THREAD

**Issue by usmansaleem** [Consensys/web3signer#1009]
More helpful error if unable to ready `--tls-keystore-file` due to permission or file not found. At the moment it throws a big stacktrace.

**Comment by eiabea** [comment]
I probably just stumbled across such an confusing error message. My keystore file is just empty and i get this:

```
2025-04-22 12:28:09.570+00:00 | pool-2-thread-1 | DEBUG | DefaultArtifactSignerProvider | Signer keys pre-loaded in memory 0
2025-04-22 12:28:09.573+00:00 | vert.x-eventloop-thread-0 | INFO  | MetricsHttpService | Metrics service started and listening on 0.0.0.0:9001
2025-04-22 12:28:09.579+00:00 | pool-2-thread-1 | INFO  | SignerLoader | Loading signer configuration metadata files from /keys
2025-04-22 12:28:09.584+00:00 | pool-2-thread-1 | INFO  | SignerLoader | Loading and converting SigningMetadata to ArtifactSigner using parallel streams ...
2025-04-22 12:28:09.589+00:00 | pool-2-thread-1 | INFO  | SignerLoader | Total Artifact Signers loaded via configuration files: 0
Total Paths cached: 0, Error count: 0
Time Taken: 00:00:00.007.
2025-04-22 12:28:09.593+00:00 | pool-2-thread-1 | INFO  | DefaultArtifactSignerProvider | Total signers (keys) currently loaded in memory: 0
Failed to initialize Web3Signer
Cause: event executor terminated
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817)
	at io.vertx.core.impl.EventLoopExecutor.execute(EventLoopExecutor.java:35)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:300)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:288)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:57)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)
	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:199)
	at io.vertx.core.http.impl.HttpServerImpl.close(HttpServerImpl.java:193)
	at org.hyperledger.besu.metrics.prometheus.MetricsHttpService.stop(MetricsHttpService.java:183)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at tech.pegasys.web3signer.core.Runner.run(Runner.java:188)
	at tech.pegasys.web3signer.core.Eth2Runner.run(Eth2Runner.java:299)
	at tech.pegasys.web3signer.commandline.subcommands.ModeSubCommand.run(ModeSubCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at tech.pegasys.web3signer.commandline.CommandlineParser.parseCommandLine(CommandlineParser.java:85)
	at tech.pegasys.web3signer.Web3SignerApp.executeWithEnvironment(Web3SignerApp.java:48)
	at tech.pegasys.web3signer.Web3SignerApp.main(Web3SignerApp.java:34)
```
