### ISSUE TITLE
Question - Read time limit on slashing database

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/web3signer#384]
Hi,

While doing an operation on the slashing database that made the old connections irresponsive, we noticed that the time limit of 60000 / 94365 ms and wondered if the 1m and 1m30s weren't a too much higher value as a read time limit in regards to missing attestation time limit.

See companion stack trace:
```
WARNING: Thread Thread[vert.x-worker-thread-3,5,main]=Thread[vert.x-worker-thread-3,5,main] has been blocked for 94365 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.8/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base@11.0.8/java.net.SocketInputStream.socketRead(Unknown Source)
	at java.base@11.0.8/java.net.SocketInputStream.read(Unknown Source)
	at java.base@11.0.8/java.net.SocketInputStream.read(Unknown Source)
	at java.base@11.0.8/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
	at java.base@11.0.8/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
	at java.base@11.0.8/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
	at java.base@11.0.8/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
	at java.base@11.0.8/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
	at app//org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
	at app//org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
	at app//org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
	at app//org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
	at app//org.postgresql.core.PGStream.receiveChar(PGStream.java:370)
	at app//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2043)
	at app//org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
	at app//org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:837)
	at app//org.postgresql.jdbc.PgConnection.commit(PgConnection.java:859)
	at app//com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:387)
	at app//com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at app//org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.commit(LocalTransactionHandler.java:125)
	at app//org.jdbi.v3.core.transaction.DelegatingTransactionHandler.commit(DelegatingTransactionHandler.java:40)
	at app//org.jdbi.v3.core.Handle.commit(Handle.java:320)
	at app//org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:210)
	at app//org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:55)
	at app//org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:89)
	at app//org.jdbi.v3.core.Handle.inTransaction(Handle.java:469)
	at app//org.jdbi.v3.core.Jdbi.lambda$inTransaction$6(Jdbi.java:415)
	at app//org.jdbi.v3.core.Jdbi$$Lambda$817/0x000000010075e040.withHandle(Unknown Source)
	at app//org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341)
	at app//org.jdbi.v3.core.Jdbi.inTransaction(Jdbi.java:415)
	at app//tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.maySignAttestation(DbSlashingProtection.java:150)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.maySign(Eth2SignForIdentifierHandler.java:176)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.signWithSlashingProtection(Eth2SignForIdentifierHandler.java:141)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.lambda$handle$0(Eth2SignForIdentifierHandler.java:107)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler$$Lambda$790/0x0000000100743040.accept(Unknown Source)
	at java.base@11.0.8/java.util.Optional.ifPresentOrElse(Unknown Source)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handleSigning(Eth2SignForIdentifierHandler.java:126)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:102)
	at app//tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:51)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$681/0x00000001006f4c40.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$269/0x00000001003a4040.run(Unknown Source)
	at java.base@11.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@11.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.8/java.lang.Thread.run(Unknown Source)``

**Comment by arash009** [comment]
We're adding two elements to address timeouts:

1. Socket timeout which will be set to 5 minutes
2. DB query timeout which will be set to 5 seconds

**Comment by pablomendezroyo** [comment]
Hey! I have faced this issue after importing around 60 validators with the slashing database. Was this issue fixed?
