### ISSUE TITLE
Deadlock on application initialization 

### ISSUE THREAD

**Issue by jmcruz1983** [ConsenSys/web3signer#412]
Happens to have 2 signers (v21.3.0) running in parallel behind a load balancer and connected to same slashing db.

So when restarting them about the same time, one of them couldn't initialize properly due to a deadlock.
Other signer runs well.

Just to highlight that pruning is wrong as signers are running with 10k keys:
```
2021-06-29 19:47:38.899+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database for 0 validators
2021-06-29 19:47:38.901+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database complete
```

Here sharing some logs:
```
2021-06-29 19:47:36.510+00:00 | ForkJoinPool.commonPool-worker-3 | INFO  | SecretAsyncClient | Retrieving secret - 0xREDACTED
2021-06-29 19:47:36.549+00:00 | reactor-http-epoll-1 | INFO  | SecretAsyncClient | Retrieved secret - 0xREDACTED
2021-06-29 19:47:36.549+00:00 | ForkJoinPool.commonPool-worker-3 | INFO  | SecretAsyncClient | Retrieving secret - 0xREDACTED
2021-06-29 19:47:36.586+00:00 | reactor-http-epoll-1 | INFO  | SecretAsyncClient | Retrieved secret - 0xREDACTED
2021-06-29 19:47:38.876+00:00 | main | ERROR | Runner | Failed to initialise application
org.jdbi.v3.core.statement.UnableToExecuteStatementException: java.sql.BatchUpdateException: Batch entry 3 INSERT INTO validators (public_key) VALUES (?)
RETURNING * was aborted: ERROR: deadlock detected
  Detail: Process 22872 waits for ShareLock on transaction 25823; blocked by process 22832.
Process 22832 waits for ShareLock on transaction 25824; blocked by process 22872.
  Hint: See server log for query details.
  Where: while inserting index tuple (73,83) in relation "validators_public_key_key"  Call getNextException to see other errors in the batch. [statement:"INSERT INTO validators (public_key) VALUES (?)", arguments:{positional:{0:0xREDACTED}, named:{}, finder:[]}]
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:228) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.statement.PreparedBatch.lambda$execute$4(PreparedBatch.java:156) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:104) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:228) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:284) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:273) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at tech.pegasys.web3signer.slashingprotection.dao.ValidatorsDao.registerValidators(ValidatorsDao.java:44) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.lambda$registerValidators$3(DbSlashingProtection.java:244) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:208) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:55) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:89) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:469) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Handle.useTransaction(Handle.java:487) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.lambda$useTransaction$7(Jdbi.java:437) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:357) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:437) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.registerValidators(DbSlashingProtection.java:230) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.Eth2Runner.lambda$loadSigners$0(Eth2Runner.java:199) ~[web3signer-core-21.3.0.jar:21.3.0]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at tech.pegasys.web3signer.core.Eth2Runner.lambda$loadSigners$1(Eth2Runner.java:198) ~[web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.multikey.DefaultArtifactSignerProvider.reload(DefaultArtifactSignerProvider.java:50) ~[web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.multikey.DefaultArtifactSignerProvider.<init>(DefaultArtifactSignerProvider.java:41) ~[web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.Eth2Runner.loadSigners(Eth2Runner.java:157) ~[web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.Eth2Runner.populateRouter(Eth2Runner.java:111) ~[web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.Runner.run(Runner.java:109) [web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.core.Eth2Runner.run(Eth2Runner.java:208) [web3signer-core-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.commandline.subcommands.ModeSubCommand.run(ModeSubCommand.java:28) [web3signer-commandline-21.3.0.jar:21.3.0]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine.access$1100(CommandLine.java:145) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [picocli-4.5.1.jar:4.5.1]
	at picocli.CommandLine.execute(CommandLine.java:2058) [picocli-4.5.1.jar:4.5.1]
	at tech.pegasys.web3signer.commandline.CommandlineParser.parseCommandLine(CommandlineParser.java:85) [web3signer-commandline-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.Web3SignerApp.executeWithEnvironment(Web3SignerApp.java:50) [web3signer-app-21.3.0.jar:21.3.0]
	at tech.pegasys.web3signer.Web3SignerApp.main(Web3SignerApp.java:35) [web3signer-app-21.3.0.jar:21.3.0]
Caused by: java.sql.BatchUpdateException: Batch entry 3 INSERT INTO validators (public_key) VALUES (?)
RETURNING * was aborted: ERROR: deadlock detected
  Detail: Process 22872 waits for ShareLock on transaction 25823; blocked by process 22832.
Process 22832 waits for ShareLock on transaction 25824; blocked by process 22872.
  Hint: See server log for query details.
  Where: while inserting index tuple (73,83) in relation "validators_public_key_key"  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:159) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1392) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1417) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:496) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1563) ~[postgresql-42.2.14.jar:42.2.14]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:?]
	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:220) ~[jdbi3-core-3.14.4.jar:3.14.4]
	... 40 more
	Suppressed: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 22872 waits for ShareLock on transaction 25823; blocked by process 22832.
Process 22832 waits for ShareLock on transaction 25824; blocked by process 22872.
  Hint: See server log for query details.
  Where: while inserting index tuple (73,83) in relation "validators_public_key_key"
		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1392) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1417) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:496) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874) ~[postgresql-42.2.14.jar:42.2.14]
		at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1563) ~[postgresql-42.2.14.jar:42.2.14]
		at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.5.jar:?]
		at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:?]
		at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:220) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.statement.PreparedBatch.lambda$execute$4(PreparedBatch.java:156) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.result.ResultProducers.lambda$getGeneratedKeys$4(ResultProducers.java:104) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:228) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:284) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:273) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at tech.pegasys.web3signer.slashingprotection.dao.ValidatorsDao.registerValidators(ValidatorsDao.java:44) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.lambda$registerValidators$3(DbSlashingProtection.java:244) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
		at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:208) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:55) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:89) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Handle.inTransaction(Handle.java:469) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Handle.useTransaction(Handle.java:487) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Jdbi.lambda$useTransaction$7(Jdbi.java:437) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:357) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at org.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:437) ~[jdbi3-core-3.14.4.jar:3.14.4]
		at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.registerValidators(DbSlashingProtection.java:230) ~[web3signer-slashing-protection-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.Eth2Runner.lambda$loadSigners$0(Eth2Runner.java:199) ~[web3signer-core-21.3.0.jar:21.3.0]
		at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
		at tech.pegasys.web3signer.core.Eth2Runner.lambda$loadSigners$1(Eth2Runner.java:198) ~[web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.multikey.DefaultArtifactSignerProvider.reload(DefaultArtifactSignerProvider.java:50) ~[web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.multikey.DefaultArtifactSignerProvider.<init>(DefaultArtifactSignerProvider.java:41) ~[web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.Eth2Runner.loadSigners(Eth2Runner.java:157) ~[web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.Eth2Runner.populateRouter(Eth2Runner.java:111) ~[web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.Runner.run(Runner.java:109) [web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.core.Eth2Runner.run(Eth2Runner.java:208) [web3signer-core-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.commandline.subcommands.ModeSubCommand.run(ModeSubCommand.java:28) [web3signer-commandline-21.3.0.jar:21.3.0]
		at picocli.CommandLine.executeUserObject(CommandLine.java:1919) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine.access$1100(CommandLine.java:145) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [picocli-4.5.1.jar:4.5.1]
		at picocli.CommandLine.execute(CommandLine.java:2058) [picocli-4.5.1.jar:4.5.1]
		at tech.pegasys.web3signer.commandline.CommandlineParser.parseCommandLine(CommandlineParser.java:85) [web3signer-commandline-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.Web3SignerApp.executeWithEnvironment(Web3SignerApp.java:50) [web3signer-app-21.3.0.jar:21.3.0]
		at tech.pegasys.web3signer.Web3SignerApp.main(Web3SignerApp.java:35) [web3signer-app-21.3.0.jar:21.3.0]
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 22872 waits for ShareLock on transaction 25823; blocked by process 22832.
Process 22832 waits for ShareLock on transaction 25824; blocked by process 22872.
  Hint: See server log for query details.
  Where: while inserting index tuple (73,83) in relation "validators_public_key_key"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1392) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1417) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:496) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874) ~[postgresql-42.2.14.jar:42.2.14]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1563) ~[postgresql-42.2.14.jar:42.2.14]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:?]
	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:220) ~[jdbi3-core-3.14.4.jar:3.14.4]
	... 40 more
2021-06-29 19:47:38.899+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database for 0 validators
2021-06-29 19:47:38.901+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database complete
2021-06-30 19:47:38.896+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database for 0 validators
2021-06-30 19:47:38.896+00:00 | pool-2-thread-1 | INFO  | DbSlashingProtection | Pruning slashing protection database complete
```

Don't hesitate to ask for original logs.
Thanks.

**Comment by usmansaleem** [comment]
Fixed in #416. Instead of creating prepared batch and issuing multiple select/insert queries, introduced pg function which performs "upsert". Tested with 90000 parallel loading of validators from two instances of web3signer.
