### ISSUE TITLE
Build failure - Task :slashing-protection:referencetests:test FAILED

### ISSUE THREAD

**Issue by benjaminion** [ConsenSys/web3signer#497]
Trying a clean Web3Signer build from scratch, a test fails, both on `21.10.5` and `master`.

Platform: Ubuntu 20.04.3 LTS

```
> java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

The build:
```
tmp> git clone https://github.com/ConsenSys/web3signer.git
tmp> cd web3signer
web3signer> git checkout 21.10.5
web3signer> ./gradlew build

> Task :common:compileJava
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.errorprone.util.ErrorProneTokens$CommentSavingTokenizer (file:/home/ben/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_check_api/2.7.1/a5c57d5d53072146104214028f894a8e9511fa87/error_prone_check_api-2.7.1.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader
WARNING: Please consider reporting this to the maintainers of com.google.errorprone.util.ErrorProneTokens$CommentSavingTokenizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :slashing-protection:referencetests:test

ReferenceTestRunner > executeEachReferenceTestFile() > tech.pegasys.web3signer.slashingprotection.ReferenceTestRunner.initializationError FAILED
    java.lang.IllegalArgumentException at ReferenceTestRunner.java:103

1 test completed, 1 failed

> Task :slashing-protection:referencetests:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':slashing-protection:referencetests:test'.
> There were failing tests. See the report at: file:///tmp/web3signer/slashing-protection/referencetests/build/reports/tests/test/index.html

...

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 18s
91 actionable tasks: 91 executed
```

The exception:
```
java.lang.IllegalArgumentException: resource slashing-protection-interchange-tests/tests/generated not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.common.io.Resources.getResource(Resources.java:195)
	at tech.pegasys.web3signer.slashingprotection.ReferenceTestRunner.executeEachReferenceTestFile(ReferenceTestRunner.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
```

**Comment by usmansaleem** [comment]
@benjaminion Can you try to initialize submodules to see if it helps?
`git submodule update --init --recursive`

**Comment by benjaminion** [comment]
Yep, that did it, thanks 🙂 

Might be good to have some basic build instructions on the repo (I should probably have read the docs, but, you know...). Just that one, `./gradlew build` and `./gradlew distDocker` would be helpful.
