### ISSUE TITLE
database timeout during import

### ISSUE THREAD

**Issue by usmansaleem** [ConsenSys/web3signer#607]
Creating new issue as reported by @pablomendezroyo in #384.

[pablomendezroyo](https://github.com/pablomendezroyo) commented 

> Hey! I have faced this issue after importing around 60 validators with the slashing database. Was this issue fixed?
> Is there any way to increase the timeout?
> I am about to do a new test running web3signer with the option --slashing-protection-db-pool-configuration-file enabled and the following config file:

`dataSource.socketTimeout=600`

> Clients may produce big slashing databases (up to 75 MB with just 22 keys), especially if running them without a pruning feature. The databases produced and exported in the client contains the data from all the keys that are validating at that time.
> 
> UPDATE
> 
> No success with that config file, again the following error

~~~
2022-07-06 07:34:57.912+00:00 | vertx-blocked-thread-checker | WARN  | BlockedThreadChecker | Thread Thread[vert.x-worker-thread-13,5,main] has been blocked for 60401 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.Net.poll(Native Method) ~[?:?]
	at sun.nio.ch.NioSocketImpl.park(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedRead(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.implRead(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(Unknown Source) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(Unknown Source) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Unknown Source) ~[?:?]
	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:453) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2119) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166) ~[postgresql-42.3.3.jar:42.3.3]
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:155) ~[postgresql-42.3.3.jar:42.3.3]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-3.4.5.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar:?]
	at org.jdbi.v3.core.statement.SqlStatement$$Lambda$434/0x0000000800445e58.invoke(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1668) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.statement.Query$$Lambda$405/0x0000000800425238.get(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.result.ResultProducers.lambda$getResultSet$2(ResultProducers.java:64) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultProducers$$Lambda$406/0x0000000800425460.get(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:54) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable$$Lambda$424/0x00000008004291b8.iterator(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:228) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:284) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:273) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at tech.pegasys.web3signer.slashingprotection.dao.SignedAttestationsDao.findSurroundedAttestations(SignedAttestationsDao.java:99) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.validator.AttestationValidator.surroundsExistingAttestation(AttestationValidator.java:135) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.AttestationImporter.importFrom(AttestationImporter.java:84) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer.importAttestations(InterchangeV5Importer.java:162) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer.parseValidator(InterchangeV5Importer.java:142) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer.lambda$importDataInternal$0(InterchangeV5Importer.java:108) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer$$Lambda$727/0x00000008005cbbe8.useHandle(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.HandleConsumer$$Lambda$729/0x00000008005ce238.withHandle(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.transaction.LocalTransactionHandler$BoundLocalTransactionHandler.inTransaction(LocalTransactionHandler.java:208) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:55) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:424) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Handle.useTransaction(Handle.java:436) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.lambda$useTransaction$5(Jdbi.java:390) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi$$Lambda$728/0x00000008005ce000.useHandle(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.HandleConsumer.lambda$asCallback$0(HandleConsumer.java:32) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.HandleConsumer$$Lambda$729/0x00000008005ce238.withHandle(Unknown Source) ~[?:?]
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:357) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at org.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:390) ~[jdbi3-core-3.14.4.jar:3.14.4]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer.importDataInternal(InterchangeV5Importer.java:103) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Importer.importDataWithFilter(InterchangeV5Importer.java:77) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.interchange.InterchangeV5Manager.importDataWithFilter(InterchangeV5Manager.java:66) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.slashingprotection.DbSlashingProtection.importDataWithFilter(DbSlashingProtection.java:110) ~[web3signer-slashing-protection-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.core.service.http.handlers.keymanager.imports.ImportKeystoresHandler.handle(ImportKeystoresHandler.java:145) ~[web3signer-core-22.6.0.jar:22.6.0]
	at tech.pegasys.web3signer.core.service.http.handlers.keymanager.imports.ImportKeystoresHandler.handle(ImportKeystoresHandler.java:52) ~[web3signer-core-22.6.0.jar:22.6.0]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
	at io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$700/0x00000008005b2228.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl$$Lambda$580/0x0000000800544000.handle(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
	at io.vertx.core.impl.ContextImpl$$Lambda$578/0x000000080053f898.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
~~~

**Comment by siladu** [comment]
Hi @pablomendezroyo sorry for the slow response, just following up on this.

We release some performance improvements to the slashing protection import back in https://github.com/ConsenSys/web3signer/releases/tag/22.11.0

Are you on that version or later now and are you still experiencing the issue?

**Comment by siladu** [comment]
Thanks @pablomendezroyo, closing this for now. Feel free to reopen if it happens again.
