### ISSUE TITLE
Is mev-boost expected to work?

### ISSUE THREAD

**Issue by yorickdowne** [ConsenSys/web3signer#637]
With Lighthouse VC 3.1.0 on Goerli, web3signer 22.8.1 does not relish `--builder-proposals`

```
2022-09-01 08:50:24.684+00:00 | vert.x-eventloop-thread-0 | ERROR | LogErrorHandler | Failed request: http://web3signer:6174/api/v1/eth2/sign/0x940a2bd7c06fa04464156bcbad5474dca1f5028311e4a9de003398869e43e85a5cb87e57bf9b1ace6f7aa2ef25faeb37
java.lang.IllegalArgumentException: Signing root 0x0db449118fc6fc10164f1c878651258762a1cd3c5463a8b1e467fff2c60e8f42 must match signing computed signing root 0x6f44c4466c5e95af7dc734c2d47dc6d29608aba810fd4fdccda9b7275899f7df from data
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:435) ~[guava-31.0.1-jre.jar:?]
        at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:105) ~[web3signer-core-22.8.1.jar:22.8.1]
        at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:58) ~[web3signer-core-22.8.1.jar:22.8.1]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.3.1.jar:4.3.1]
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[vertx-core-4.3.1.jar:4.3.1]
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:101) ~[vertx-core-4.3.1.jar:4.3.1]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[vertx-core-4.3.1.jar:4.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

If this is expected to work, I can get you trace logs for web3signer and the VC

**Comment by siladu** [comment]
Hi @yorickdowne, yes mev-boost is expected to work, although I can't attest to that exact version of Lighthouse. 
We've seen that error before when there is a difference in the network configuration between VC and web3signer. Just want to rule that out in case it's the same issue :)

See https://docs.web3signer.consensys.net/en/latest/HowTo/Get-Started/Start-Web3Signer/#public-testnets

The pertinent part is to configure the goerli network as part of the web3signer eth2 subcommand, i.e.  `web3signer eth2 --network=goerli`

**Comment by siladu** [comment]
Do you know what it was attempting to sign when it got the error: validator registration, attestation, block proposal, etc?

**Comment by siladu** [comment]
> I can get you trace logs for web3signer and the VC
this would certainly help yes please :)

**Comment by yorickdowne** [comment]
> Do you know what it was attempting to sign when it got the error: validator registration, attestation, block proposal, etc?

Registration

As for trace logs - yes shall, it might be next week. Preparing to travel tomorrow.

**Comment by yorickdowne** [comment]
Oh yeah you hit the nail on the head. My deployment does not specify network. I shall fix that! 

Closing and thanks for giving it some attention. I asked Stakewise to amend their docs.

**Comment by siladu** [comment]
Thanks for reporting back, it's a common error. We've updated our docs recently to hopefully make it clearer but the UX could be a lot better for this, we have some stories in our backlog to improve!

**Comment by yorickdowne** [comment]
`Sep 02 00:33:37.931 INFO Published validator registrations to the builder network, count: 100, service: preparation`

Huzzah.

**Comment by yorickdowne** [comment]
Looking at logs: Printing the configured network right after the version line would improve UX and make mis-configurations easier to detect

**Comment by siladu** [comment]
Thanks for the feedback @yorickdowne - I agree.

We also have a similar story https://github.com/ConsenSys/web3signer/issues/614

Shame we couldn't get to it before the merge releases 😅

**Comment by siladu** [comment]
> Looking at logs: Printing the configured network right after the version line would improve UX and make mis-configurations easier to detect

@yorickdowne FYI https://github.com/ConsenSys/web3signer/issues/640 is included in the latest release https://github.com/ConsenSys/web3signer/releases/tag/22.10.0
