### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by tbenr** [ConsenSys/web3signer#772]
When starting up web3signer, after loading keys, the service may stop with the following stacktrace:
```
2023-04-19 22:17:04.667+00:00 | main | ERROR | Runner | Failed to initialise application
java.util.concurrent.ExecutionException: io.vertx.ext.web.openapi.RouterBuilderException: Cannot load the spec in path file:///tmp/w3s_openapi_17095143643154225637/eth2/web3signer.yaml
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
    at tech.pegasys.web3signer.core.Runner.getRouterBuilder(Runner.java:232) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.core.Runner.run(Runner.java:138) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.core.Eth2Runner.run(Eth2Runner.java:375) ~[web3signer-core-23.3.1.jar:23.3.1]
    at tech.pegasys.web3signer.commandline.subcommands.ModeSubCommand.run(ModeSubCommand.java:28) ~[web3signer-commandline-23.3.1.jar:23.3.1]
    at picocli.CommandLine.executeUserObject(CommandLine.java:1939) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine.access$1300(CommandLine.java:145) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) ~[picocli-4.6.2.jar:4.6.2]
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) ~[picocli-4.6.2.jar:4.6.2]
Caused by: io.vertx.ext.web.openapi.RouterBuilderException: Cannot load the spec in path file:///tmp/w3s_openapi_17095143643154225637/eth2/web3signer.yaml
    at io.vertx.ext.web.openapi.RouterBuilderException.createInvalidSpecFile(RouterBuilderException.java:50) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at io.vertx.ext.web.openapi.RouterBuilder.lambda$create$0(RouterBuilder.java:243) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.Composition$1.onFailure(Composition.java:66) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FailedFuture.addListener(FailedFuture.java:98) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.Composition.onFailure(Composition.java:55) ~[vertx-core-4.3.8.jar:4.3.8]
    at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[vertx-core-4.3.8.jar:4.3.8]
Caused by: java.lang.IllegalStateException: Recursive update
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763) ~[?:?]
    at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.resolveExternalRef(OpenAPIHolderImpl.java:267) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
    at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
    at io.vertx.ext.web.openapi.impl.OpenAPIHolderImpl.walkAndSolve(OpenAPIHolderImpl.java:208) ~[vertx-web-openapi-4.3.8.jar:4.3.8]
  ```

**Comment by jframe** [comment]
What version of the JDK is being used? Does this happen every time? Haven't been able to reproduce the issue locally, unfortunately.

Could you try testing on the latest develop version of web3signer? We recently updated the Vertx dependency library version which might fix this issue.
