### ISSUE TITLE
Timeout when loading keys from Azure vault

### ISSUE THREAD

**Issue by jasonyic** [Consensys/web3signer#797]
Hi Team, we are facing the following issue once in a while when web-signer starts:
we are using azuere key vault and running latest 23.3.1, should this Timeout be configurable ?

 ```
2023-06-02 08:48:54.513+00:00 | reactor-http-epoll-1 | WARN  | HttpClientConnect | [b5fbfc78-1732, L:/10.5.1.5:51382 - R:az-jpeast-00-prod-kv.vault.azure.net/10.5.2.4:443] The connection observed an error
java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.responseTimedOut(ResponseTimeoutHandler.java:58) ~[azure-core-http-netty-1.13.1.jar:1.13.1]
	at com.azure.core.http.netty.implementation.ResponseTimeoutHandler.lambda$handlerAdded$0(ResponseTimeoutHandler.java:45) ~[azure-core-http-netty-1.13.1.jar:1.13.1]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) [netty-transport-classes-epoll-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.89.Final.jar:4.1.89.Final]
	at java.lang.Thread.run(Unknown Source) [?:?]
2023-06-02 08:48:54.515+00:00 | pool-2-thread-1 | ERROR | NettyAsyncHttpClient | java.util.concurrent.TimeoutException: Channel response timed out after 60000 milliseconds.
```

Note to dev: See `tech.pegasys.signers.azure.AzureKeyVault`
The timeout should be applied both from bulk mode cli option as well as metadata config files.
See example: https://github.com/Azure/azure-sdk-for-java/wiki/%5BManagement%5D-Configuration

**Comment by usmansaleem** [comment]
Hi @jasonyic, apologies for late reply. Let me have a look at Azure libraries about setting response timeout and get back to you.
