### ISSUE TITLE
Flaky signatureIsDerivedFromP1363Encoded test

### ISSUE THREAD

**Issue by jframe** [Consensys/web3signer#943]
The Eth1SignatureUtilTest.signatureIsDerivedFromP1363Encoded has been intermittingly failing in CI.

It is failing with the stack trace
```
java.lang.RuntimeException: Could not construct a recoverable key. Are your credentials valid?
	at tech.pegasys.web3signer.signing.secp256k1.util.Eth1SignatureUtil.deriveSignature(Eth1SignatureUtil.java:84)
	at tech.pegasys.web3signer.signing.secp256k1.util.Eth1SignatureUtil.deriveSignatureFromP1363Encoded(Eth1SignatureUtil.java:65)
	at tech.pegasys.web3signer.signing.secp256k1.util.Eth1SignatureUtilTest.signatureIsDerivedFromP1363Encoded(Eth1SignatureUtilTest.java:80)
```

**Comment by jframe** [comment]
Haven't seen this for awhile so closing it. Will open if we see it again
