### ISSUE TITLE
Fork at slot * does not support sync committees

### ISSUE THREAD

**Issue by lyfsn** [Consensys/web3signer#957]
Hello,

I was testing the functionality of web3signer in a local private network and encountered repeated errors when using geth+lighthouse with web3signer. The errors are as follows:

```
2024-01-02 06:16:57.248+00:00 | vert.x-eventloop-thread-0 | ERROR | LogErrorHandler | Failed request: http://host.docker.internal:49000/api/v1/eth2/sign/0x81b676591b823270a3284ace7d81cbce2d6cdce55bb0e053874d7e3a08f729453009d3e662ec3130379f43c0f3210b6d
2024-01-02 14:16:57 java.lang.IllegalStateException: Fork at slot 787 does not support sync committees
2024-01-02 14:16:57     at tech.pegasys.teku.spec.Spec.lambda$getSyncCommitteeUtilRequired$1(Spec.java:176) ~[spec-23.10.0.jar:23.10.0]
2024-01-02 14:16:57     at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
2024-01-02 14:16:57     at tech.pegasys.teku.spec.Spec.getSyncCommitteeUtilRequired(Spec.java:174) ~[spec-23.10.0.jar:23.10.0]
2024-01-02 14:16:57     at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.signingRootFromSyncCommitteeUtils(Eth2SignForIdentifierHandler.java:358) ~[web3signer-core-23.11.0.jar:23.11.0]
2024-01-02 14:16:57     at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.computeSigningRoot(Eth2SignForIdentifierHandler.java:300) ~[web3signer-core-23.11.0.jar:23.11.0]
2024-01-02 14:16:57     at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:100) ~[web3signer-core-23.11.0.jar:23.11.0]
2024-01-02 14:16:57     at tech.pegasys.web3signer.core.service.http.handlers.signing.eth2.Eth2SignForIdentifierHandler.handle(Eth2SignForIdentifierHandler.java:56) ~[web3signer-core-23.11.0.jar:23.11.0]
2024-01-02 14:16:57     at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[vertx-web-4.4.4.jar:4.4.4]
2024-01-02 14:16:57     at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137) ~[vertx-core-4.4.4.jar:4.4.4]
2024-01-02 14:16:57     at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264) ~[vertx-core-4.4.4.jar:4.4.4]
2024-01-02 14:16:57     at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135) ~[vertx-core-4.4.4.jar:4.4.4]
2024-01-02 14:16:57     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
2024-01-02 14:16:57     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
2024-01-02 14:16:57     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.100.Final.jar:4.1.100.Final]
2024-01-02 14:16:57     at java.lang.Thread.run(Unknown Source) [?:?]
```

On the Lighthouse side, the error message is:

```
2024-01-02 14:09:51 Jan 02 06:09:51.649 WARN Unable to sign selection proof          slot: 787, pubkey: 0x996323af7e545fb6363ace53f1538c7ddc3eb0d985b2479da3ee4ace10cbc393b518bf02d1a2ddb2f5bdf09b473933ea, error: UnableToSign(Web3SignerRequestFailed("HTTP status server error (500 Internal Server Error) for url (http://host.docker.internal:49000/api/v1/eth2/sign/0x996323af7e545fb6363ace53f1538c7ddc3eb0d985b2479da3ee4ace10cbc393b518bf02d1a2ddb2f5bdf09b473933ea)")), service: duties
```

Due to the voluminous error logs, there is a significant consumption of disk space. I am looking for a way to resolve this issue.

Is this error related to web3signer, Lighthouse, or something else?

**Comment by lyfsn** [comment]
Additionally, the following error occurred with Prysm:
```
time="2024-01-02 06:45:24" level=error msg="Could not get validator roles" error="could not check if a validator is a sync committee aggregator: http: ContentLength=392 with Body length 0" prefix=validator slot=35477
```

**Comment by lyfsn** [comment]
This error causes the Sync Agg % to always be zero.

![image](https://github.com/Consensys/web3signer/assets/141099829/0624234f-6768-4ba6-ac28-1e1f8f5c7371)

**Comment by jframe** [comment]
hi @lyfsn, Can you share your config for lighthouse and web3signer? And what versions you are using of lighthouse and web3signer?

**Comment by lyfsn** [comment]
@jframe j
The version currently in use is: (docker image)

-geth:  `ethereum/client-go:latest`
-lighthouse: `sigp/lighthouse:latest`
-web3signer: `consensys/web3signer:23.11.0`

I will provide more specific configuration details later, I'm still considering which specific configurations to include.

The startup parameters for web3signer are:

```
  web3signer-1:
    image: consensys/web3signer:23.11.0
    restart: always
    command:
      - --http-host-allowlist=*
      - eth2
      - --keystores-path=/validator_keys
      - --keystores-password-file=/password.txt
      - --slashing-protection-enabled=false
    ports:
      - "49000:9000"
    volumes:
      - ./validator_keys:/validator_keys
      - ./password.txt:/password.txt
```

The startup parameters for lighthouse validator are:
```
  validator:
    image: sigp/lighthouse:latest
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator_keys
      - --http
      - --http-address=0.0.0.0
      - --http-port=5062
      - --unencrypted-http-transport
      - --init-slashing-protection
      - --beacon-nodes=http://beacon:5052
      - --suggested-fee-recipient=0x6D39C4E60dEf1DfC6d09A8FdB5D075e85F0e5F8d
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5064
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./validator_keys:/validator_keys
    ports:
      - "5062:5062"
      - "5064:5064"
    depends_on:
      - beacon
    restart: unless-stopped
```

**Comment by jframe** [comment]
@lyfsn, In your web3signer startup parameters, you need to specify your custom network configuration file for web3signer. Without specifying the network web3signer will default to mainnet.

The --network parameter https://docs.web3signer.consensys.io/reference/cli/subcommands#network can take the file path to a yaml configuration file in the same format as used in the consensus clients.

**Comment by lyfsn** [comment]
It's indeed an issue with the `network` parameter, this was a very big mistake on my part, thank you so much for your help!
